import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation} from '../dist/engine.js';
function balanced(s){assert.equal(s.auditReciprocal(),true);for(const e of Object.values(s.entities)){const b=s.balance(e);assert.equal(b.A,b.L+b.E);}const c=s.consolidated;assert.equal(c.A,c.L+c.E);}
test('credit creates matching loan, deposit, debt and land without reserves',()=>{const s=new Simulation();s.revalue('s2');const reserves=s.reserves,broad=s.broad,loans=s.amount('bank','loans');const child=s.originate(4,2,'s2');assert.equal(s.reserves,reserves);assert.equal(s.broad,broad+100);assert.equal(s.amount('bank','loans'),loans+100);assert.deepEqual(s.balance(child),{A:100,L:100,E:0});balanced(s);});
test('revaluation increases only property and subsidiary equity',()=>{const s=new Simulation(),bank={...s.bank.accounts},broad=s.broad;s.revalue('s2');assert.deepEqual(s.balance('s2'),{A:400,L:100,E:300});assert.deepEqual(s.bank.accounts,bank);assert.equal(s.broad,broad);balanced(s);});
test('clearing nets reciprocal flows and conserves reserves',()=>{const s=new Simulation();s.endDay();const plan=s.clearingPlan,reserves=s.reserves,broad=s.broad,income=s.income;s.endDay();assert.equal(s.reserves,reserves+income-plan.net);assert.equal(s.broad,broad-plan.incoming);assert.ok(plan.incoming>0);balanced(s);});
test('receipts exhaust the finite treasury exactly',()=>{const s=new Simulation();for(let i=0;i<420;i++)s.collect();assert.equal(s.amount('treasury','reserves'),0);const reserve=s.reserves;s.collect();assert.equal(s.reserves,reserve);balanced(s);});
test('default, absorption and isolation recognize each credit loss once',()=>{for(const action of ['absorb','isolate']){const s=new Simulation();s.impair(s.entities.s2,65);s.refreshProvision();assert.equal(s.balance('bank').E,185);s[action]('s2');assert.equal(s.balance('bank').E,action==='absorb'?160:185);assert.equal(s.amount('bank','allowance'),0);assert.ok(s.balance('s2').E>=0);balanced(s);}});
test('capital freeze uses an exact 8 percent boundary',()=>{const s=Object.create(Simulation.prototype);s.entities={bank:{accounts:{loans:250,capital:20,deposits:230}}};s.status='active';assert.equal(s.car,8);assert.equal(s.creditFrozen,false);s.bank.accounts.capital=19;s.bank.accounts.deposits=231;assert.equal(s.creditFrozen,true);});
test('unbalanced or unmatched postings roll back',()=>{const s=new Simulation();const before=JSON.stringify(s.bank.accounts);assert.throws(()=>s.post('invalid',[['bank','loans',100,0],['bank','deposits',0,100]]),/Loans/);assert.equal(JSON.stringify(s.bank.accounts),before);balanced(s);});
test('liquidity recovery consumes a day and applies utility stress',()=>{const s=new Simulation();s.revalue('s2');s.revalue('s2');s.post('Reserve loss',[['bank','reserves',0,175],['bank','retained',175,0],['treasury','reserves',175,0],['treasury','retained',0,175]]);s.pending=50;s.pendingPlan={outgoing:50,incoming:0,net:50};s.status='liquidity';const day=s.day,value=s.amount('s2','property');s.endDay();assert.equal(s.day,day+1);assert.equal(s.settledDays,0);assert.equal(s.status,'liquidity');assert.ok(s.amount('s2','property')<value);assert.equal(s.amount('bank','deposits'),100);balanced(s);});
test('bank capital exhaustion collapses towers without deleting debt history',()=>{const s=new Simulation();s.post('Capital loss',[['bank','reserves',0,180],['bank','retained',180,0],['treasury','reserves',180,0],['treasury','retained',0,180]]);s.impair(s.entities.s2,0);s.refreshProvision();s.check();assert.equal(s.status,'meltdown');assert.equal(s.amount('s2','debt'),100);assert.equal(s.amount('s2','property'),0);balanced(s);});
test('a complete playable strategy wins after twelve funded settlements',()=>{const s=new Simulation();for(const[x,y]of[[5,3],[6,3],[6,2]])s.buildUtility(x,y);s.revalue('s2');const child=s.originate(4,2,'s2');while(s.entities.s2.level<3)s.revalue('s2');while(child.level<3)s.revalue(child.id);s.endDay();s.buildUtility(3,3);s.buildUtility(2,3);s.endDay();s.buildUtility(2,4);s.endDay();s.buildUtility(1,4);s.buildUtility(1,3);s.endDay();s.buildUtility(0,4);while(s.settledDays<12)s.endDay();assert.equal(s.won,true);assert.equal(s.status,'active');assert.equal(s.footprint,12);assert.ok(s.totals.E>=6000);balanced(s);});
test('seeded action sequences preserve entity, reciprocal and consolidated books',()=>{let seed=71237;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};let successful=0;for(let game=0;game<30;game++){const s=new Simulation();for(let turn=0;turn<180;turn++){const e=s.tiles[Math.floor(random()*s.tiles.length)],action=Math.floor(random()*8);try{if(action===0)s.revalue(e.id);if(action===1)s.endDay();if(action===2)s.buildUtility(Math.floor(random()*8),Math.floor(random()*8));if(action===3)s.originate(e.x+(random()<.5?1:-1),e.y,e.id);if(action===4)s.upgrade(e.id);if(action===5)s.sell(e.id);if(action===6)s.absorb(e.id);if(action===7)s.isolate(e.id);successful++;}catch{}balanced(s);}}assert.ok(successful>500);});
